baseURL = 'https://moto6.github.io/blog'
languageCode = 'en-us'
title = 'blog'
enableSearch = true
codeLineNumbers = true
codeMaxLines = 15
theme = 'PaperMod'
publishDir = "docs"

[author]
name = "Kim"
